In [3]:
import numpy as np

In [12]:
lista1 = [1, 2, 'abad', 5, {"k":"v"}]
lista2 = [100, 2000, 'xyz']


In [13]:
lista1 + lista2

[1, 2, 'abad', 5, {'k': 'v'}, 100, 2000, 'xyz']

In [11]:
tablica = np.array( [1, 2, 5] )
tablica

array([1, 2, 5])

In [14]:
tablica1 = np.array( [1, 2, 5] )
tablica2 = np.array( [100, 200, 500] )

In [15]:
tablica1 + tablica2

array([101, 202, 505])

In [16]:
print(lista1)
print(tablica2)

[1, 2, 'abad', 5, {'k': 'v'}]
[100 200 500]


In [17]:
lista_list = [  [1, 2, 3],  [4, 5, 6] ]
lista_list

[[1, 2, 3], [4, 5, 6]]

In [22]:
len(lista_list)

2

In [34]:
macierz = np.array(   [  [1, 0, 6],  [4, 5, 6] ]  )
macierz

array([[1, 0, 6],
       [4, 5, 6]])

In [21]:
len(macierz)

2

In [27]:
macierz.all()

np.False_

In [28]:
macierz.any()

np.True_

In [31]:
macierz.max()

6


In [32]:
macierz.sum()

np.int64(19)

In [35]:
macierz.argmax()

np.int64(2)

In [36]:
macierz.argmin()

np.int64(1)

In [37]:
macierz.flatten()

array([1, 0, 6, 4, 5, 6])

In [39]:
macierz.reshape(1,6)

array([[1, 0, 6, 4, 5, 6]])

In [40]:
macierz.reshape(6,1)

array([[1],
       [0],
       [6],
       [4],
       [5],
       [6]])

In [41]:
macierz.reshape(3,2)

array([[1, 0],
       [6, 4],
       [5, 6]])

In [42]:
macierz.reshape(2,3)

array([[1, 0, 6],
       [4, 5, 6]])

In [43]:
macierz.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [44]:
macierz.T

array([[1, 4],
       [0, 5],
       [6, 6]])

In [56]:
m_zer = np.zeros( (10, 10), dtype=np.int8 )
m_zer[ 5, 6] = 32
m_zer

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 32,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [55]:
m_jedynek = np.ones( (10,10) ) 
m_jedynek

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
np.diag( (10, 10, 50, 60, 10 ) )

array([[10,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0],
       [ 0,  0, 50,  0,  0],
       [ 0,  0,  0, 60,  0],
       [ 0,  0,  0,  0, 10]])

In [58]:
m_zer - m_jedynek

array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., 31., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])

In [59]:
np.linspace(1,32,63)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. ])

In [63]:
x = np.linspace(-10, 10, 50)
y = np.sin(x)

In [64]:
x

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [65]:
y

array([ 0.54402111,  0.16628279, -0.23877532, -0.60460332, -0.8710967 ,
       -0.99447137, -0.9544572 , -0.75762842, -0.43632343, -0.04333173,
        0.35677924,  0.6982724 ,  0.92504137,  0.99982867,  0.91034694,
        0.67129779,  0.32195632, -0.08028167, -0.46932961, -0.78126802,
       -0.96484631, -0.98990308, -0.85232157, -0.57470604, -0.20266794,
        0.20266794,  0.57470604,  0.85232157,  0.98990308,  0.96484631,
        0.78126802,  0.46932961,  0.08028167, -0.32195632, -0.67129779,
       -0.91034694, -0.99982867, -0.92504137, -0.6982724 , -0.35677924,
        0.04333173,  0.43632343,  0.75762842,  0.9544572 ,  0.99447137,
        0.8710967 ,  0.60460332,  0.23877532, -0.16628279, -0.54402111])

In [66]:
np.ones( (10,10,5,7) ) 

array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 

In [67]:
np.array([1, 2, 3, 4], ndmin=5)

array([[[[[1, 2, 3, 4]]]]])

In [70]:
macierz

array([[1, 0, 6],
       [4, 5, 6]])

In [77]:
macierz[:, 1] 

array([0, 5])